# CI: test -> (on tag v*) pack -> publish to NuGet
# Queue on pushes/PRs to main/master, and on tags that look like v1.2.3
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - master
  tags:
    include:
      - 'v*'

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

variables:
  BUILD_CONFIGURATION: 'Release'
  CSPROJ_PATH: 'AzureBlueSolutions.Json.NET.csproj'
  ARTIFACTS_DIR: 'artifacts'
  TAG_PREFIX: 'v'

stages:
- stage: Test
  displayName: Build & Test
  jobs:
    - job: test
      displayName: dotnet test
      steps:
        - checkout: self
          clean: true
          fetchDepth: 0

        - task: UseDotNet@2
          displayName: Use .NET 8 SDK
          inputs:
            packageType: sdk
            version: 8.x

        - script: |
            set -euo pipefail
            dotnet --info
            dotnet restore
            dotnet build --configuration "$(BUILD_CONFIGURATION)" --no-restore
            # run all tests and collect trx results
            dotnet test --configuration "$(BUILD_CONFIGURATION)" --no-build --logger "trx;LogFileName=test.trx"
          displayName: Restore, Build, Test

        - task: PublishTestResults@2
          displayName: Publish test results
          inputs:
            testResultsFiles: '**/test.trx'
            testResultsFormat: VSTest
            failTaskOnFailedTests: true

- stage: Pack
  displayName: Pack on tag
  dependsOn: Test
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  jobs:
    - job: pack
      displayName: dotnet pack
      steps:
        - checkout: self
          clean: true
          fetchDepth: 0

        - task: UseDotNet@2
          displayName: Use .NET 8 SDK
          inputs:
            packageType: sdk
            version: 8.x

        - script: |
            set -euo pipefail

            # Extract tag name and derive version without the 'v' prefix
            TAG_REF="$(Build.SourceBranch)"             # e.g., refs/tags/v0.1.3
            TAG_NAME="${TAG_REF##refs/tags/}"           # v0.1.3
            VERSION="${TAG_NAME#${TAG_PREFIX}}"         # 0.1.3

            echo "Detected tag: ${TAG_NAME} -> package version: ${VERSION}"

            dotnet restore
            dotnet build --configuration "$(BUILD_CONFIGURATION)" --no-restore

            mkdir -p "$(ARTIFACTS_DIR)"

            # Ensure the package version matches the tag
            dotnet pack "$(CSPROJ_PATH)" \
              -c "$(BUILD_CONFIGURATION)" \
              -o "$(ARTIFACTS_DIR)" \
              --no-build \
              /p:PackageVersion="${VERSION}" \
              /p:ContinuousIntegrationBuild=true

            echo "Packed artifacts:"
            ls -la "$(ARTIFACTS_DIR)"
          displayName: Pack with tag version

        - publish: $(ARTIFACTS_DIR)
          artifact: nupkgs
          displayName: Publish nupkg artifacts

- stage: Publish
  displayName: Publish to NuGet.org
  dependsOn: Pack
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  jobs:
    - job: push
      displayName: dotnet nuget push
      steps:
        - download: current
          artifact: nupkgs
          displayName: Download packed nupkgs

        - task: UseDotNet@2
          displayName: Use .NET 8 SDK
          inputs:
            packageType: sdk
            version: 8.x

        - script: |
            set -euo pipefail
            NUGET_SOURCE="${NUGET_SOURCE:-https://api.nuget.org/v3/index.json}"

            echo "Pushing packages in $(Pipeline.Workspace)/nupkgs to ${NUGET_SOURCE}"
            shopt -s nullglob
            for pkg in "$(Pipeline.Workspace)/nupkgs"/*.nupkg; do
              echo "Pushing $pkg"
              dotnet nuget push "$pkg" \
                --api-key "$(NUGET_API_KEY)" \
                --source "$NUGET_SOURCE" \
                --skip-duplicate
            done
          displayName: Push to NuGet.org